CREATE TABLE IF NOT EXISTS reference_data.sub_bge (
    id                serial PRIMARY KEY,
    code              text NOT NULL UNIQUE,
    name              text NOT NULL,
    description       text,
    bge_id            integer NOT NULL REFERENCES reference_data.bge(id),
    entity_type       text NOT NULL DEFAULT 'sub_org' CHECK (entity_type IN ('sub_org', 'service_designee')),
    parent_sub_bge_id integer REFERENCES reference_data.sub_bge(id),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);

INSERT INTO reference_data.sub_bge (code, name, bge_id, entity_type) VALUES
    ('Attorney General',                            'Attorney General',                            (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Citizens Services',                           'Citizens Services',                           (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Emergency Management and Climate Readiness',  'Emergency Management and Climate Readiness',  (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Energy and Climate Solutions',                'Energy and Climate Solutions',                (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Environment and Parks',                       'Environment and Parks',                       (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Forests',                                      'Forests',                                      (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Health',                                       'Health',                                       (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Housing and Municipal Affairs',                'Housing and Municipal Affairs',                (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Indigenous Relations and Reconciliation',      'Indigenous Relations and Reconciliation',      (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Jobs Economic Development and Innovation',     'Jobs Economic Development and Innovation',     (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Labour',                                        'Labour',                                        (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Post-Secondary Education and Future Skills',   'Post-Secondary Education and Future Skills',   (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Social Development and Poverty Reduction',     'Social Development and Poverty Reduction',     (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Tourism Arts Culture and Sport',                'Tourism Arts Culture and Sport',                (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Transportation and Transit',                    'Transportation and Transit',                    (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Land and Water BC',                             'Land and Water BC',                             (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Infrastructure',                                'Infrastructure',                                (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Finance',                                       'Finance',                                       (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Office of the Premier',                         'Office of the Premier',                         (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('BC Public Service Agency',                      'BC Public Service Agency',                      (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'sub_org'),
    ('Education and Child Care',                      'Education and Child Care',                      (SELECT id FROM reference_data.bge WHERE code = 'ECC'), 'sub_org'),
    ('BC Hydro',                                      'BC Hydro',                                      (SELECT id FROM reference_data.bge WHERE code = 'BC Hydro'), 'sub_org'),
    ('BCLC',                                          'BC Lottery Corporation',                        (SELECT id FROM reference_data.bge WHERE code = 'BCLC'), 'sub_org'),
    ('ICBC',                                          'Insurance Corporation of BC',                   (SELECT id FROM reference_data.bge WHERE code = 'ICBC'), 'sub_org'),
    ('FHA',                                           'Fraser Health Authority',                       (SELECT id FROM reference_data.bge WHERE code = 'FHA'), 'sub_org'),
    ('PHSA',                                          'Provincial Health Services Authority',          (SELECT id FROM reference_data.bge WHERE code = 'PHSA'), 'sub_org'),
    ('VIHA',                                          'Vancouver Island Health Authority',             (SELECT id FROM reference_data.bge WHERE code = 'VIHA'), 'sub_org'),
    ('School District 71',                            'School District 71',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 33',                            'School District 33',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 35',                            'School District 35',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 38',                            'School District 38',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 40',                            'School District 40',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 42',                            'School District 42',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 43',                            'School District 43',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 51',                            'School District 51',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 72',                            'School District 72',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 83',                            'School District 83',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 93',                            'School District 93',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 34',                            'School District 34',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 36',                            'School District 36',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org'),
    ('School District 67',                            'School District 67',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'), 'sub_org')
ON CONFLICT (code) DO NOTHING;

-- after the sub_org insert above so the parent lookups below can resolve.
INSERT INTO reference_data.sub_bge (code, name, bge_id, entity_type, parent_sub_bge_id) VALUES
    ('BC Financial Services Authority', 'BC Financial Services Authority', (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'service_designee', (SELECT id FROM reference_data.sub_bge WHERE code = 'Citizens Services')),
    ('BC Family Maintenance Agency',    'BC Family Maintenance Agency',    (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'service_designee', (SELECT id FROM reference_data.sub_bge WHERE code = 'Citizens Services')),
    ('BC Assessment',                   'BC Assessment',                   (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'service_designee', (SELECT id FROM reference_data.sub_bge WHERE code = 'Citizens Services')),
    ('BC LDB',                          'BC Liquor Distribution Branch',   (SELECT id FROM reference_data.bge WHERE code = 'Gov BC'), 'service_designee', (SELECT id FROM reference_data.sub_bge WHERE code = 'Citizens Services')),
    ('Providence Health Care',          'Providence Health Care',          (SELECT id FROM reference_data.bge WHERE code = 'VCHA (+PHC)'), 'service_designee', NULL),
    ('Powertech',                       'Powertech Labs',                  (SELECT id FROM reference_data.bge WHERE code = 'BC Hydro'), 'service_designee', NULL),
    ('Power Ex',                        'Powerex',                         (SELECT id FROM reference_data.bge WHERE code = 'BC Hydro'), 'service_designee', NULL)
ON CONFLICT (code) DO NOTHING;
