CREATE TABLE IF NOT EXISTS reference_data.sub_bge (
    id          serial PRIMARY KEY,
    code        text NOT NULL UNIQUE,
    name        text NOT NULL,
    description text,
    bge_id      integer NOT NULL REFERENCES reference_data.bge(id),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

INSERT INTO reference_data.sub_bge (code, name, bge_id) VALUES
    ('BC Financial Services Authority',             'BC Financial Services Authority',             (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Attorney General',                            'Attorney General',                            (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Citizens Services',                           'Citizens Services',                           (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Emergency Management and Climate Readiness',  'Emergency Management and Climate Readiness',  (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Energy and Climate Solutions',                'Energy and Climate Solutions',                (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Environment and Parks',                       'Environment and Parks',                       (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Forests',                                      'Forests',                                      (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Health',                                       'Health',                                       (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Housing and Municipal Affairs',                'Housing and Municipal Affairs',                (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Indigenous Relations and Reconciliation',      'Indigenous Relations and Reconciliation',      (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Jobs Economic Development and Innovation',     'Jobs Economic Development and Innovation',     (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Labour',                                        'Labour',                                        (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Post-Secondary Education and Future Skills',   'Post-Secondary Education and Future Skills',   (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Social Development and Poverty Reduction',     'Social Development and Poverty Reduction',     (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Tourism Arts Culture and Sport',                'Tourism Arts Culture and Sport',                (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Transportation and Transit',                    'Transportation and Transit',                    (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Land and Water BC',                             'Land and Water BC',                             (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Infrastructure',                                'Infrastructure',                                (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Finance',                                       'Finance',                                       (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Office of the Premier',                         'Office of the Premier',                         (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('BC Public Service Agency',                      'BC Public Service Agency',                      (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('BC Family Maintenance Agency',                  'BC Family Maintenance Agency',                  (SELECT id FROM reference_data.bge WHERE code = 'Gov BC')),
    ('Education and Child Care',                      'Education and Child Care',                      (SELECT id FROM reference_data.bge WHERE code = 'ECC')),
    ('BC Hydro',                                      'BC Hydro',                                      (SELECT id FROM reference_data.bge WHERE code = 'BC Hydro')),
    ('BCLC',                                          'BC Lottery Corporation',                        (SELECT id FROM reference_data.bge WHERE code = 'BCLC')),
    ('ICBC',                                          'Insurance Corporation of BC',                   (SELECT id FROM reference_data.bge WHERE code = 'ICBC')),
    ('FHA',                                           'Fraser Health Authority',                       (SELECT id FROM reference_data.bge WHERE code = 'FHA')),
    ('Providence Health Care',                        'Providence Health Care',                        (SELECT id FROM reference_data.bge WHERE code = 'VCHA (+PHC)')),
    ('PHSA',                                          'Provincial Health Services Authority',          (SELECT id FROM reference_data.bge WHERE code = 'PHSA')),
    ('VIHA',                                          'Vancouver Island Health Authority',             (SELECT id FROM reference_data.bge WHERE code = 'VIHA')),
    ('School District 71',                            'School District 71',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 33',                            'School District 33',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 35',                            'School District 35',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 38',                            'School District 38',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 40',                            'School District 40',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 42',                            'School District 42',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 43',                            'School District 43',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 51',                            'School District 51',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 72',                            'School District 72',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 83',                            'School District 83',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 93',                            'School District 93',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 34',                            'School District 34',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 36',                            'School District 36',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts')),
    ('School District 67',                            'School District 67',                            (SELECT id FROM reference_data.bge WHERE code = 'School Districts'))
ON CONFLICT (code) DO NOTHING;
