sonar.projectKey=bcgov_Data-Management-Platform
sonar.organization=bcgov-sonarcloud

sonar.sources=app/backend,app/frontend/src
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/.pytest_cache/**,**/public/**

sonar.tests=app/backend/tests,app/frontend/src
sonar.test.inclusions=**/*test*.py,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.python.version=3.11
sonar.python.xunit.reportPath=reports/backend-test-results.xml
sonar.python.coverage.reportPaths=reports/backend-coverage.xml

sonar.javascript.lcov.reportPaths=reports/frontend-lcov.info
sonar.typescript.lcov.reportPaths=reports/frontend-lcov.info
