-- DDL moved to app/backend/alembic/raw_data/ngta_postgres.sql
-- Apply with: cd app/backend && alembic upgrade head
-- (or: docker compose -f app/docker-compose.yml run --rm backend alembic upgrade head)
