# mappings.py

BGE_MAP = {

    "BRITISH COLUMBIA LOTTERY CORPORATION": "BCLC",
    "BRITISH COLOMBIA LOTTERY CORPORATION": "BCLC",
    "BC LOTTERY CORPORATION": "BCLC",
    "BC LOTTERY": "BCLC",

    "BC HYDRO": "BC HYDRO",
    "BRITISH COLUMBIA HYDRO": "BC HYDRO",

    "EDUCATION AND CHILD CARE": "ECC",

    "FRASER HEALTH AUTHORITY": "FHA",
    "INTERIOR HEALTH AUTHORITY": "IHA",
    "NORTHERN HEALTH AUTHORITY": "NHA",

    "INSURANCE CORPORATION OF BRITISH COLUMB.": "ICBC",

    "PROVINCIAL HEALTH SERVICES AUTHORITY": "PHSA",

    "VANCOUVER COASTAL HEALTH AUTHORITY": "VCHA",
    
    "VANCOUVER ISLAND HEALTH AUTHORITY": "VIHA",

    "BC GOVERNMENT MINISTRIES": "GOV BC",
}

# ======== SUB-BGE → BGE CONTROLLED MAP ==============================

SUB_BGE_TO_BGE = {

    # GOV BC
    "BC MIN ATTORNEY GENERAL": "GOV BC",
    "INDIGENOUS RELATIONS AND RECONCILIATION": "GOV BC",
    "MINISTRY OF CITIZENS SERVICES": "GOV BC",
    "MINISTRY OF INFRASTRUCTURE": "GOV BC",
    "MIN OF SOCIAL DEVELOPMENT": "GOV BC",
    "BC MIN AGRICULTURE & FOOD": "GOV BC",
    "BC MIN CHILDREN & FAMILY DEVELOPMENT": "GOV BC",
    "BC MIN CITIZENS' SERVICES": "GOV BC",
    "BC MIN EDUCATION & CHILDCARE": "GOV BC",
    "BC MIN EMERG MGMT & CLIMATE READINESS": "GOV BC",
    "BC MIN ENERGY & CLIMATE SOLUTIONS": "GOV BC",
    "BC MIN ENVIRONMENT AND PARKS": "GOV BC",
    "BC MIN FINANCE": "GOV BC",
    "BC MIN FORESTS": "GOV BC",
    "BC MIN HEALTH": "GOV BC",
    "BC MIN HOUSING & MUNICIPAL AFFAIRS": "GOV BC",
    "BC MIN JOBS & ECONOMIC GROWTH": "GOV BC",
    "BC MIN LABOUR": "GOV BC",
    "BC MIN MINING & CRITICAL MINERALS": "GOV BC",
    "BC MIN POST-SECONDARY ED & FUTURE SKILLS": "GOV BC",
    "BC MIN PUBLIC SAFETY & SOLICITOR GEN": "GOV BC",
    "BC MIN SOCIAL DEV & POVERTY REDUCTION": "GOV BC",
    "BC MIN TOURISM, ARTS, CULTURE, AND SPORT": "GOV BC",
    "BC MIN TRANSPORTATION & TRANSIT": "GOV BC",
    "BC MIN WATER LAND & RESOURCE STEWARD": "GOV BC",
    "BC OFFICE OF THE PREMIER": "GOV BC",
    "BC PUBLIC SERVICE AGENCY": "GOV BC",
    "BC ASSESSMENT": "GOV BC",
    "BC LDB": "GOV BC",
    "BC FAMILY MAINTENANCE AGENCY LTD.": "GOV BC",
    "BC FINANCIAL SERVICES AUTHORITY": "GOV BC",

    "BC MIN ENERGY AND CLIMATE SOLUTIONS": "GOV BC",
    "BC MIN HOUSING AND MUNICIPAL AFFAIRS": "GOV BC",
    "HOUSING AND MUNICIPAL AFFAIRS": "GOV BC",
    "BC MIN INDIGENOUS RELATIONS & RECONCIL.": "GOV BC",
    "BC MIN JOBS AND ECONOMIC GROWTH": "GOV BC",
    "JOB ECONOMIC DEVELOPMENT AND INNOVATION": "GOV BC",
    "TRANSPORTATION AND TRANSIT": "GOV BC",
    "BC FINANCIAL SERVICE AUTH.": "GOV BC",
    "MIN OF FINANCE BC": "GOV BC",
    "OFFICE OF THE PREMIER": "GOV BC",
    "LAND AND WATER BC INC": "GOV BC",

    "PROVIDENCE HEALTH CARE": "VCHA",
    # BC HYDRO
    "POWERTECH": "BC HYDRO",
    "POWER EX": "BC HYDRO",
}
