# mapping.py

from utils import normalize

BGE_MAP = {
    "BC GOVERNMENT MINISTRIES": "GOV BC",
    "BRITISH COLUMBIA LOTTERY CORPORATION": "BCLC",
    "BC LOTTERY CORPORATION": "BCLC",
    "BC LOTTERY": "BCLC",

    "BC HYDRO": "BC HYDRO",
    "BRITISH COLUMBIA HYDRO": "BC HYDRO",

    "EDUCATION AND CHILD CARE": "ECC",
    "BC MIN EDUCATION AND CHILD CARE": "ECC",
    "BC MIN EDUCATION & CHILD CARE": "ECC",
    "FRASER HEALTH AUTHORITY": "FHA",
    "INTERIOR HEALTH AUTHORITY": "IHA",
    "NORTHERN HEALTH AUTHORITY": "NHA",

    "INSURANCE CORPORATION OF BRITISH COLUMB.": "ICBC",

    "PROVINCIAL HEALTH SERVICES AUTHORITY": "PHSA",

    "VANCOUVER COASTAL HEALTH AUTHORITY": "VCHA",
    
    "VANCOUVER ISLAND HEALTH AUTHORITY": "VIHA",

    "WORKSAFE BC": "WORKSAFE BC",
    "FRASER NATIONS HEALTH AUTHORITY": "FNHA",
}

SUB_BGE_TO_BGE = {

    # Government Ministries
    "BC MIN AGRICULTURE AND FOOD": "GOV BC",
    "BC MIN ATTORNEY GENERAL": "GOV BC",
    "BC MIN CHILDREN AND FAMILY DEVELOPMENT": "GOV BC",
    "BC MIN CITIZENS SERVICES": "GOV BC",
    "BC MIN EDUCATION AND CHILDCARE": "GOV BC",
    "BC MIN EMERG MGMT AND CLIMATE READINESS": "GOV BC",
    "BC MIN ENERGY AND CLIMATE SOLUTIONS": "GOV BC",
    "BC MIN ENVIRONMENT AND PARKS": "GOV BC",
    "BC MIN FINANCE": "GOV BC",
    "BC MIN FORESTS": "GOV BC",
    "BC MIN HEALTH": "GOV BC",
    "BC MIN HOUSING AND MUNICIPAL AFFAIRS": "GOV BC",
    "BC MIN INDIGENOUS RELATIONS AND RECONCILIATION": "GOV BC",
    "BC MIN INFRASTRUCTURE": "GOV BC",
    "BC MIN JOBS AND ECONOMIC GROWTH": "GOV BC",
    "BC MIN LABOUR": "GOV BC",
    "BC MIN MINING AND CRITICAL MINERALS": "GOV BC",
    "BC MIN POST SECONDARY ED AND FUTURE SKILLS": "GOV BC",
    "BC MIN PUBLIC SAFETY AND SOLICITOR GEN": "GOV BC",
    "BC MIN SOCIAL DEV AND POVERTY REDUCTION": "GOV BC",
    "BC MIN TOURISM ARTS CULTURE AND SPORT": "GOV BC",
    "BC MIN TRANSPORTATION AND TRANSIT": "GOV BC",
    "BC MIN WATER LAND AND RESOURCE STEWARD": "GOV BC",
    "BC OFFICE OF THE PREMIER": "GOV BC",

    # Agencies
    "BC PUBLIC SERVICE AGENCY": "GOV BC",
    "BC ASSESSMENT": "GOV BC",
    "BC LDB": "GOV BC",
    "BC FAMILY MAINTENANCE AGENCY LTD": "GOV BC",
    "BC FINANCIAL SERVICES AUTHORITY": "GOV BC",
    "LAND AND WATER BC INC": "GOV BC",
    "BC Housing Management Commission": "GOV BC",
    "BC Office of Human Rights Commissioner": "GOV BC",
    "BC Pension": "GOV BC",
    "Community Living BC": "GOV BC",
    "Destination BC": "GOV BC",
    "Elections BC": "GOV BC",
    "Forest Practice Board": "GOV BC",
    "Islands Trust Conservancy": "GOV BC",
    "LEGISLATIVE ASSEMBLY": "GOV BC",
    "OFFICE OF THE AUDITOR GENERAL OF B C": "GOV BC",
    "OFFICE OF THE INFORMATION & PRIVACY COMMISSIONER": "GOV BC",
    "OFFICE OF THE MERIT COMMISSIONER": "GOV BC",
    "OFFICE OF THE OMBUDSPERSON": "GOV BC",
    "OFFICE OF THE POLICE COMPLAINT COMMISSIONER": "GOV BC",
    "OFFICE OF THE REPRESENTATIVE FOR CHILDREN AND YOUTH": "GOV BC",
    "Public Guardian and Trustee": "GOV BC",
    "ROYAL B C MUSEUM": "GOV BC",
    "Superior Court Judiciary Branch": "GOV BC",
    "TI Corp": "GOV BC",

    # BC Hydro
    "POWERTECH": "BC HYDRO",
    "POWER EX": "BC HYDRO",

    # VCHA
    "PROVIDENCE HEALTH CARE": "VCHA",
}
SUB_BGE_ALIASES = {

    # Ministries
    "LABOUR": "BC MIN LABOUR",

    "MINISTRY OF INFRASTRUCTURE":
        "BC MIN INFRASTRUCTURE",

    "MINISTRY OF CITIZENS SERVICES":
        "BC MIN CITIZENS SERVICES",

    "OFFICE OF THE PREMIER":
        "BC OFFICE OF THE PREMIER",

    "HOUSING AND MUNICIPAL AFFAIRS":
        "BC MIN HOUSING AND MUNICIPAL AFFAIRS",

    "INDIGENOUS RELATIONS AND RECONCILIATION":
        "BC MIN INDIGENOUS RELATIONS AND RECONCILIATION",

    "SOCIAL DEVELOPMENT AND POVERTY REDUCTION":
        "BC MIN SOCIAL DEV AND POVERTY REDUCTION",

    "TOURISM ARTS CULTURE AND SPORT":
        "BC MIN TOURISM ARTS CULTURE AND SPORT",

    "TRANSPORTATION AND TRANSIT":
        "BC MIN TRANSPORTATION AND TRANSIT",

    "POST SECONDARY EDUCATION AND FUTURE SKILLS":
        "BC MIN POST SECONDARY ED AND FUTURE SKILLS",

    "JOB ECONOMIC DEVELOPMENT AND INNOVATION":
        "BC MIN JOBS AND ECONOMIC GROWTH",

    "MIN OF FINANCE BC":
        "BC MIN FINANCE",

    "MIN OF SOCIAL DEVELOPMENT":
        "BC MIN SOCIAL DEV AND POVERTY REDUCTION",

    # Different punctuation
    "BC FAMILY MAINTENANCE AGENCY LTD.":
        "BC FAMILY MAINTENANCE AGENCY LTD",

    "BC FINANCIAL SERVICE AUTH":
        "BC FINANCIAL SERVICES AUTHORITY",

    "BC FINANCIAL SERVICES AUTH":
        "BC FINANCIAL SERVICES AUTHORITY",

    "BC MIN INDIGENOUS RELATIONS AND RECONCIL":
        "BC MIN INDIGENOUS RELATIONS AND RECONCILIATION",

    # "&" vs "AND"
    "BC MIN AGRICULTURE & FOOD":
        "BC MIN AGRICULTURE AND FOOD",

    "BC MIN CHILDREN & FAMILY DEVELOPMENT":
        "BC MIN CHILDREN AND FAMILY DEVELOPMENT",

    "BC MIN EDUCATION & CHILDCARE":
        "BC MIN EDUCATION AND CHILDCARE",

    "BC MIN EMERG MGMT & CLIMATE READINESS":
        "BC MIN EMERG MGMT AND CLIMATE READINESS",

    "BC MIN JOBS & ECONOMIC GROWTH":
        "BC MIN JOBS AND ECONOMIC GROWTH",

    "BC MIN POST-SECONDARY ED & FUTURE SKILLS":
        "BC MIN POST SECONDARY ED AND FUTURE SKILLS",

    "BC MIN PUBLIC SAFETY & SOLICITOR GEN":
        "BC MIN PUBLIC SAFETY AND SOLICITOR GEN",

    "BC MIN SOCIAL DEV & POVERTY REDUCTION":
        "BC MIN SOCIAL DEV AND POVERTY REDUCTION",

    "BC MIN TOURISM, ARTS, CULTURE, AND SPORT":
        "BC MIN TOURISM ARTS CULTURE AND SPORT",

    "BC MIN TRANSPORTATION & TRANSIT":
        "BC MIN TRANSPORTATION AND TRANSIT",

    "BC MIN WATER LAND & RESOURCE STEWARD":
        "BC MIN WATER LAND AND RESOURCE STEWARD",

    "BC MIN HOUSING & MUNICIPAL AFFAIRS":
        "BC MIN HOUSING AND MUNICIPAL AFFAIRS",

    "BC MIN CITIZEN'S SERVICES":
        "BC MIN CITIZENS SERVICES",

    "BC MIN CITIZENS' SERVICES":
        "BC MIN CITIZENS SERVICES",

    "BC MIN CITIZENS' SERVICE":
        "BC MIN CITIZENS SERVICES",

    "BC MIN CITIZENS SERVICE":
        "BC MIN CITIZENS SERVICES",
}

# normalize mappings once
BGE_MAP = {normalize(k): normalize(v) for k, v in BGE_MAP.items()}
SUB_BGE_TO_BGE = {normalize(k): normalize(v) for k, v in SUB_BGE_TO_BGE.items()}
SUB_BGE_ALIASES = {
    normalize(k): normalize(v)
    for k, v in SUB_BGE_ALIASES.items()
}
#VALID_PRODUCTLINE = ["DATA", "VOICE", "N/A"]
TOLERANCE = 0.01