{{- if and (not .Values.backend.existingSecret) .Values.backend.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conn-tap.backendName" . }}
  labels:
    {{- include "conn-tap.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
