apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "conn-tap.frontendName" . }}
  labels:
    {{- include "conn-tap.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  {{- range $key, $value := .Values.frontend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
