name: check conventional commits

permissions:
  contents: read

on:
  workflow_call:

jobs:
  cocogitto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Print to be removed
        shell: bash
        run: |
          echo "github.event_name=${{ github.event_name }}"
          echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          echo "github.base_ref=${{ github.base_ref }}"
          echo "github.head_ref=${{ github.head_ref }}"

      - name: Tag the base ref for pull requests
        shell: bash
        working-directory: .
        if: github.event_name == 'pull_request'
        run: git checkout "$GITHUB_BASE_REF" && git tag latest && git checkout "$GITHUB_HEAD_REF"
      - name: Conventional commits check
        uses: cocogitto/cocogitto-action@v4
        with:
          command: check
          args: --from-latest-tag

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: ./.bin/install-gitleaks-linux-x64.sh
      - run: ./gitleaks detect --exit-code 0 --report-format sarif --report-path "gitleaks.sarif"
      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "gitleaks.sarif"
