name: main

permissions:
  contents: read

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-conventional-commits:
    uses: ./.github/workflows/check-conventional-commits.yml

  run-tests:
    uses: ./.github/workflows/run-tests.yml
