name: main

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write

on:
  workflow_call:
  # to be removed after initial setup and testing
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-conventional-commits:
    uses: ./.github/workflows/check-conventional-commits.yml

  run-tests:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
